// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetConnectionStatus():Promise<Record<string, any>>;

export function GetMetaChampions():Promise<main.MetaData>;

export function RegisterToggleHotkey():Promise<void>;

export function ToggleWindow():Promise<void>;
