// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConnectionStatus():Promise<Record<string, any>>;

export function RegisterToggleHotkey():Promise<void>;

export function ToggleWindow():Promise<void>;
