// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetConnectionStatus() {
  return window['go']['main']['App']['GetConnectionStatus']();
}

export function GetMetaChampions() {
  return window['go']['main']['App']['GetMetaChampions']();
}

export function RegisterToggleHotkey() {
  return window['go']['main']['App']['RegisterToggleHotkey']();
}

export function ToggleWindow() {
  return window['go']['main']['App']['ToggleWindow']();
}
